[package]
name = "bib-extract"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
thiserror.workspace = true
pdf_oxide.workspace = true
pdf-extract.workspace = true

[dev-dependencies]
bib-core = { path = "../bib-core" }
tempfile.workspace = true
